// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sarenza.DAL.Data;

#nullable disable

namespace Sarenza.DAL.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20221108152750_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("Sarenza.Core.Entities.History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("TemperatureC")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("History");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2022, 11, 8, 15, 27, 50, 715, DateTimeKind.Utc).AddTicks(9423),
                            TemperatureC = 22.0
                        });
                });

            modelBuilder.Entity("Sarenza.Core.Entities.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ColdTemperature")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("HotTemperature")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColdTemperature = 22.0,
                            CreationDateTime = new DateTime(2022, 11, 8, 15, 27, 50, 715, DateTimeKind.Utc).AddTicks(9247),
                            HotTemperature = 40.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
