// <auto-generated />
using System;
using CarbonSarenza.Web.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarbonSarenza.Web.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("CarbonSarenza.Web.Domain.Entities.History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("TemperatureC")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("History");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2022, 11, 7, 10, 25, 22, 617, DateTimeKind.Local).AddTicks(2382),
                            TemperatureC = 22.0
                        });
                });

            modelBuilder.Entity("CarbonSarenza.Web.Domain.Entities.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ColdTemperature")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("HotTemperature")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColdTemperature = 22.0,
                            CreationDateTime = new DateTime(2022, 11, 7, 10, 25, 22, 617, DateTimeKind.Local).AddTicks(2278),
                            HotTemperature = 40.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
